
input {
  file {
    path => "/app/data/logstash/input_data/data.*"
    mode => "read"
    codec => plain {
      charset => "UTF-8"
    }
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  mutate { add_field => { "field" => "value"} }
}

output {
  file {
    path => "/app/data/logstash/output_data/data"
    flush_interval => 0
    write_behavior => "overwrite"
  }
}
